[build]
  command = "npm run build"
  publish = "dist"            # or your build output folder

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]  # keeps admin as external if needed

[build.environment]
  NODE_VERSION = "20"

# Ensures Function deps get installed even if you keep a functions-only package.json (not recommended)
[[plugins]]
package = "@netlify/plugin-functions-install-core"
