[build]
  publish = "public"        # <- THIS is the key fix

# Clean, scoped redirects (no global /* rewrite)
[[redirects]]
  from = "/pump/pump"
  to = "/pump/"
  status = 301
  force = true

[[redirects]]
  from = "/pump"
  to = "/pump/index.html"
  status = 200

[[redirects]]
  from = "/pump/"
  to = "/pump/index.html"
  status = 200

[[redirects]]
  from = "/pump/*"
  to = "/pump/index.html"
  status = 200

[[redirects]]
  from = "/geophoto/viewer"
  to = "/geophoto/viewer/index.html"
  status = 200

[[redirects]]
  from = "/geophoto/viewer/*"
  to = "/geophoto/viewer/index.html"
  status = 200
