[build]
  command = "npm run build"
  publish = "public"   # change if your static files live elsewhere

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
