[functions]
  # Pick ONE folder. If your function file is at /functions/ai-image.js, use this:
  directory = "functions"

# Make the nice /api/ path hit the Netlify function too.
[[redirects]]
  from = "/api/ai-image"
  to = "/.netlify/functions/ai-image"
  status = 200
  force = true
