# Redirect old /pump/pump to /pump/
[[redirects]]
  from = "/pump/pump"
  to = "/pump/"
  status = 301
  force = true

# Optional: SPA fallback for the pump tool (remove if not needed)
[[redirects]]
  from = "/pump/*"
  to = "/pump/index.html"
  status = 200

# Optional: SPA fallback for the main site (remove if not needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
