[build]
  # Serve the site from /public (you have public/index.html, public/geophoto/*, etc.)
  publish = "public"

[functions]
  # Your ai-image.js is in /functions
  directory = "functions"

# Nice API path that maps to the function
[[redirects]]
  from = "/api/ai-image"
  to = "/.netlify/functions/ai-image"
  status = 200
  force = false
