# netlify.toml
[build]
  # No build step: just succeed and let Netlify publish /public
  command = "echo Building static site"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]  # add others only if you import them

[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Pretty functions path (optional)
[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
