# keep your existing content ABOVE/BELOW — do not delete it

[functions]
  # point to the ONE folder you actually use
  directory = "functions"      # or "netlify/functions" if that's where ai-image.js lives

# Map only this exact path to the function (nothing else).
[[redirects]]
  from = "/api/ai-image"
  to = "/.netlify/functions/ai-image"
  status = 200
  force = false
