[build]
  # Serve your static site from /public (matches your zip)
  publish = "public"

[functions]
  # Your Netlify Functions are in /functions
  directory = "functions"

# Pretty alias so both URLs work
[[redirects]]
  from = "/api/ai-image"
  to = "/.netlify/functions/ai-image"
  status = 200
  force = false
