# Redirect old /pump/pump links to the pump entry
[[redirects]]
  from = "/pump/pump"
  to = "/pump/"
  status = 301
  force = true

# Pump entry + optional client routes
[[redirects]]
  from = "/pump"
  to = "/pump/index.html"
  status = 200

[[redirects]]
  from = "/pump/"
  to = "/pump/index.html"
  status = 200

[[redirects]]
  from = "/pump/*"
  to = "/pump/index.html"
  status = 200

# Geophoto viewer (scoped SPA fallback)
[[redirects]]
  from = "/geophoto/viewer"
  to = "/geophoto/viewer/index.html"
  status = 200

[[redirects]]
  from = "/geophoto/viewer/*"
  to = "/geophoto/viewer/index.html"
  status = 200

# IMPORTANT: no global /* → /index.html rule here.
