[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"   # fine to keep
  external_node_modules = ["firebase-admin"]

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
