# ---------- Build ----------
[build]
  command = "echo Building static site"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

# ---------- Functions ----------
[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

# ---------- Redirects (order matters) ----------
# Pretty function path
[[redirects]]
  from = "/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

# Local API proxy so your pages can call /api/ai-image
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true
