[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[build.environment]
  NODE_VERSION = "20"

# Optional: safe to keep even if you removed functions/package.json
[[plugins]]
package = "@netlify/plugin-functions-install-core"
