[[redirects]]
  from = "/pump"
  to = "/pump/pump.html"
  status = 200

[[redirects]]
  from = "/pump/*"
  to = "/pump/pump.html"
  status = 200

[[redirects]]
  from = "/pump/pump"
  to = "/pump/pump.html"
  status = 200
