[build]
  command = "echo Building static site"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  # Your logs show Netlify is picking up from "netlify/functions"
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Mark native deps external so Netlify installs them at deploy time
  external_node_modules = ["firebase-admin", "sharp"]

[[plugins]]
package = "@netlify/plugin-functions-install-core"
